-- One-time/bootstrap rebuild for a DM base date. Scans historical DWS by design.
SET 'execution.runtime-mode'='batch';
SET 'table.dml-sync'='true';
SET 'table.local-time-zone'='Asia/Shanghai';
SET 'pipeline.name'='paimon-dm-initialize-__BIZ_DATE__';
CREATE CATALOG paimon WITH ('type'='paimon','metastore'='filesystem','warehouse'='file:///warehouse/paimon');

INSERT OVERWRITE paimon.ad_dw.dm_advertiser_df
PARTITION (dt='__BIZ_DATE__')
SELECT dim.advertiser_id,dim.advertiser_name,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.delivery_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS delivery_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.delivery_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS delivery_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.delivery_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS delivery_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.delivery_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS delivery_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.impression_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS impression_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.impression_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS impression_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.impression_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS impression_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.impression_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS impression_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.click_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS click_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.click_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS click_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.click_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS click_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.click_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS click_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.conversion_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS conversion_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.conversion_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS conversion_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.conversion_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS conversion_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.conversion_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS conversion_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS cost_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS cost_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS cost_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS cost_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.closed_cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS closed_cost_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.closed_cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS closed_cost_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.closed_cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS closed_cost_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.closed_cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS closed_cost_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.ecommerce_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.ecommerce_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.ecommerce_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.ecommerce_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.short_video_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.short_video_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.short_video_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.short_video_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.live_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.live_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.live_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.live_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.live_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.live_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.live_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.live_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.live_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.live_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.live_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.live_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.live_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.live_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.live_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.live_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_gmv_acc
FROM paimon.ad_dw.dim_advertiser_df dim
LEFT JOIN paimon.ad_dw.dws_advertiser_di d ON dim.advertiser_id=d.advertiser_id AND d.dt<='__BIZ_DATE__'
GROUP BY dim.advertiser_id,dim.advertiser_name;

INSERT OVERWRITE paimon.ad_dw.dm_unit_df
PARTITION (dt='__BIZ_DATE__')
SELECT dim.unit_id,dim.unit_name,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.delivery_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS delivery_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.delivery_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS delivery_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.delivery_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS delivery_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.delivery_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS delivery_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.impression_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS impression_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.impression_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS impression_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.impression_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS impression_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.impression_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS impression_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.click_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS click_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.click_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS click_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.click_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS click_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.click_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS click_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.conversion_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS conversion_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.conversion_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS conversion_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.conversion_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS conversion_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.conversion_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS conversion_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS cost_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS cost_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS cost_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS cost_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.closed_cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS closed_cost_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.closed_cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS closed_cost_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.closed_cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS closed_cost_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.closed_cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS closed_cost_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.ecommerce_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.ecommerce_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.ecommerce_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.ecommerce_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.short_video_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.short_video_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.short_video_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.short_video_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.live_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.live_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.live_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.live_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.live_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.live_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.live_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.live_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.live_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.live_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.live_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.live_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.live_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.live_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.live_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.live_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_gmv_acc
FROM paimon.ad_dw.dim_unit_df dim
LEFT JOIN paimon.ad_dw.dws_unit_di d ON dim.unit_id=d.unit_id AND d.dt<='__BIZ_DATE__'
GROUP BY dim.unit_id,dim.unit_name;

INSERT OVERWRITE paimon.ad_dw.dm_creative_df
PARTITION (dt='__BIZ_DATE__')
SELECT dim.creative_id,dim.creative_name,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.delivery_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS delivery_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.delivery_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS delivery_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.delivery_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS delivery_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.delivery_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS delivery_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.impression_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS impression_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.impression_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS impression_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.impression_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS impression_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.impression_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS impression_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.click_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS click_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.click_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS click_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.click_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS click_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.click_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS click_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.conversion_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS conversion_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.conversion_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS conversion_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.conversion_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS conversion_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.conversion_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS conversion_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS cost_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS cost_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS cost_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS cost_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.closed_cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS closed_cost_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.closed_cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS closed_cost_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.closed_cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS closed_cost_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.closed_cost ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS closed_cost_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS pay_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS refund_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.ecommerce_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.ecommerce_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.ecommerce_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.ecommerce_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_pay_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.ecommerce_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.ecommerce_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS ecommerce_refund_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.short_video_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.short_video_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.short_video_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.short_video_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_pay_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.short_video_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.short_video_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS short_video_refund_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.live_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.live_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.live_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.live_pay_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.live_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_count_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.live_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_count_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.live_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_count_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.live_refund_order_count ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_count_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.live_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.live_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.live_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.live_pay_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_pay_order_gmv_acc,
  COALESCE(SUM(CASE WHEN d.dt='__BIZ_DATE__' THEN d.live_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_gmv_1d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_6__' AND d.dt<='__BIZ_DATE__' THEN d.live_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_gmv_7d,
  COALESCE(SUM(CASE WHEN d.dt>='__DATE_MINUS_29__' AND d.dt<='__BIZ_DATE__' THEN d.live_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_gmv_30d,
  COALESCE(SUM(CASE WHEN d.dt<='__BIZ_DATE__' THEN d.live_refund_order_gmv ELSE CAST(0 AS BIGINT) END),CAST(0 AS BIGINT)) AS live_refund_order_gmv_acc
FROM paimon.ad_dw.dim_creative_df dim
LEFT JOIN paimon.ad_dw.dws_creative_di d ON dim.creative_id=d.creative_id AND d.dt<='__BIZ_DATE__'
GROUP BY dim.creative_id,dim.creative_name;
