-- One-time destructive recreation for Fluss 0.9.1, which cannot rename columns
-- and cannot safely read pre-evolution log segments after ALTER TABLE ADD.
SET 'execution.runtime-mode'='batch';

CREATE CATALOG fluss WITH ('type'='fluss','bootstrap.servers'='fluss-coordinator:9123');
CREATE CATALOG paimon WITH (
  'type'='paimon',
  'metastore'='filesystem',
  'warehouse'='file:///warehouse/paimon'
);

USE CATALOG fluss;
USE ad_dw;
DROP TABLE IF EXISTS ads_realtime_metric_30s;
DROP TABLE IF EXISTS dws_advertiser_di;
DROP TABLE IF EXISTS dws_unit_di;
DROP TABLE IF EXISTS dws_creative_di;
DROP TABLE IF EXISTS dim_unit_df;

USE CATALOG paimon;
USE ad_dw;
DROP TABLE IF EXISTS ads_realtime_metric_30s;
DROP TABLE IF EXISTS dws_advertiser_di;
DROP TABLE IF EXISTS dws_unit_di;
DROP TABLE IF EXISTS dws_creative_di;
DROP TABLE IF EXISTS dim_unit_df;
DROP TABLE IF EXISTS ads_offline_metric_di;
DROP TABLE IF EXISTS dm_advertiser_df;
DROP TABLE IF EXISTS dm_unit_df;
DROP TABLE IF EXISTS dm_creative_df;

USE CATALOG fluss;
USE ad_dw;
CREATE TABLE dim_unit_df (
  unit_id BIGINT,unit_name STRING,campaign_id BIGINT,campaign_name STRING,status INT,is_closed INT,
  delivery_type INT,search_keyword ARRAY<STRING>,product_id BIGINT,landing_page_url STRING,
  audience STRING,start_date STRING,end_date STRING,daily_budget BIGINT,bid_type STRING,bid BIGINT,
  created_at STRING,updated_at STRING,PRIMARY KEY(unit_id) NOT ENFORCED
) WITH ('bucket.num'='4','table.datalake.enabled'='true','table.datalake.freshness'='30s');

CREATE TABLE dws_advertiser_di (
  dt STRING,advertiser_id BIGINT,advertiser_name STRING,
  delivery_count BIGINT,impression_count BIGINT,click_count BIGINT,conversion_count BIGINT,cost BIGINT,closed_cost BIGINT,pay_order_count BIGINT,refund_order_count BIGINT,pay_order_gmv BIGINT,refund_order_gmv BIGINT,ecommerce_pay_order_count BIGINT,ecommerce_refund_order_count BIGINT,ecommerce_pay_order_gmv BIGINT,ecommerce_refund_order_gmv BIGINT,short_video_pay_order_count BIGINT,short_video_refund_order_count BIGINT,short_video_pay_order_gmv BIGINT,short_video_refund_order_gmv BIGINT,live_pay_order_count BIGINT,live_refund_order_count BIGINT,live_pay_order_gmv BIGINT,live_refund_order_gmv BIGINT,
  PRIMARY KEY(dt,advertiser_id) NOT ENFORCED
) PARTITIONED BY(dt) WITH ('bucket.num'='2','table.datalake.enabled'='true','table.datalake.freshness'='30s');
CREATE TABLE dws_unit_di (
  dt STRING,unit_id BIGINT,unit_name STRING,
  delivery_count BIGINT,impression_count BIGINT,click_count BIGINT,conversion_count BIGINT,cost BIGINT,closed_cost BIGINT,pay_order_count BIGINT,refund_order_count BIGINT,pay_order_gmv BIGINT,refund_order_gmv BIGINT,ecommerce_pay_order_count BIGINT,ecommerce_refund_order_count BIGINT,ecommerce_pay_order_gmv BIGINT,ecommerce_refund_order_gmv BIGINT,short_video_pay_order_count BIGINT,short_video_refund_order_count BIGINT,short_video_pay_order_gmv BIGINT,short_video_refund_order_gmv BIGINT,live_pay_order_count BIGINT,live_refund_order_count BIGINT,live_pay_order_gmv BIGINT,live_refund_order_gmv BIGINT,
  PRIMARY KEY(dt,unit_id) NOT ENFORCED
) PARTITIONED BY(dt) WITH ('bucket.num'='2','table.datalake.enabled'='true','table.datalake.freshness'='30s');
CREATE TABLE dws_creative_di (
  dt STRING,creative_id BIGINT,creative_name STRING,
  delivery_count BIGINT,impression_count BIGINT,click_count BIGINT,conversion_count BIGINT,cost BIGINT,closed_cost BIGINT,pay_order_count BIGINT,refund_order_count BIGINT,pay_order_gmv BIGINT,refund_order_gmv BIGINT,ecommerce_pay_order_count BIGINT,ecommerce_refund_order_count BIGINT,ecommerce_pay_order_gmv BIGINT,ecommerce_refund_order_gmv BIGINT,short_video_pay_order_count BIGINT,short_video_refund_order_count BIGINT,short_video_pay_order_gmv BIGINT,short_video_refund_order_gmv BIGINT,live_pay_order_count BIGINT,live_refund_order_count BIGINT,live_pay_order_gmv BIGINT,live_refund_order_gmv BIGINT,
  PRIMARY KEY(dt,creative_id) NOT ENFORCED
) PARTITIONED BY(dt) WITH ('bucket.num'='2','table.datalake.enabled'='true','table.datalake.freshness'='30s');
CREATE TABLE ads_realtime_metric_30s (
  window_start TIMESTAMP_LTZ(3),window_end TIMESTAMP_LTZ(3),advertiser_id BIGINT,
  campaign_id BIGINT,unit_id BIGINT,creative_id BIGINT,
  delivery_count BIGINT,impression_count BIGINT,click_count BIGINT,conversion_count BIGINT,cost BIGINT,closed_cost BIGINT,pay_order_count BIGINT,refund_order_count BIGINT,pay_order_gmv BIGINT,refund_order_gmv BIGINT,ecommerce_pay_order_count BIGINT,ecommerce_refund_order_count BIGINT,ecommerce_pay_order_gmv BIGINT,ecommerce_refund_order_gmv BIGINT,short_video_pay_order_count BIGINT,short_video_refund_order_count BIGINT,short_video_pay_order_gmv BIGINT,short_video_refund_order_gmv BIGINT,live_pay_order_count BIGINT,live_refund_order_count BIGINT,live_pay_order_gmv BIGINT,live_refund_order_gmv BIGINT,dt STRING,
  PRIMARY KEY(dt,window_start,creative_id) NOT ENFORCED
) PARTITIONED BY(dt) WITH ('bucket.num'='2','table.datalake.enabled'='true','table.datalake.freshness'='30s');

USE CATALOG paimon;
USE ad_dw;
CREATE TABLE ads_offline_metric_di (
  dt STRING,advertiser_id BIGINT,campaign_id BIGINT,unit_id BIGINT,creative_id BIGINT,
  delivery_count BIGINT,impression_count BIGINT,click_count BIGINT,conversion_count BIGINT,cost BIGINT,closed_cost BIGINT,pay_order_count BIGINT,refund_order_count BIGINT,pay_order_gmv BIGINT,refund_order_gmv BIGINT,ecommerce_pay_order_count BIGINT,ecommerce_refund_order_count BIGINT,ecommerce_pay_order_gmv BIGINT,ecommerce_refund_order_gmv BIGINT,short_video_pay_order_count BIGINT,short_video_refund_order_count BIGINT,short_video_pay_order_gmv BIGINT,short_video_refund_order_gmv BIGINT,live_pay_order_count BIGINT,live_refund_order_count BIGINT,live_pay_order_gmv BIGINT,live_refund_order_gmv BIGINT,
  PRIMARY KEY(dt,creative_id) NOT ENFORCED
) PARTITIONED BY(dt) WITH ('bucket'='2','file.format'='parquet');

CREATE TABLE dm_advertiser_df (
  dt STRING,advertiser_id BIGINT,advertiser_name STRING,
  delivery_count_1d BIGINT,
  delivery_count_7d BIGINT,
  delivery_count_30d BIGINT,
  delivery_count_acc BIGINT,
  impression_count_1d BIGINT,
  impression_count_7d BIGINT,
  impression_count_30d BIGINT,
  impression_count_acc BIGINT,
  click_count_1d BIGINT,
  click_count_7d BIGINT,
  click_count_30d BIGINT,
  click_count_acc BIGINT,
  conversion_count_1d BIGINT,
  conversion_count_7d BIGINT,
  conversion_count_30d BIGINT,
  conversion_count_acc BIGINT,
  cost_1d BIGINT,
  cost_7d BIGINT,
  cost_30d BIGINT,
  cost_acc BIGINT,
  closed_cost_1d BIGINT,
  closed_cost_7d BIGINT,
  closed_cost_30d BIGINT,
  closed_cost_acc BIGINT,
  pay_order_count_1d BIGINT,
  pay_order_count_7d BIGINT,
  pay_order_count_30d BIGINT,
  pay_order_count_acc BIGINT,
  refund_order_count_1d BIGINT,
  refund_order_count_7d BIGINT,
  refund_order_count_30d BIGINT,
  refund_order_count_acc BIGINT,
  pay_order_gmv_1d BIGINT,
  pay_order_gmv_7d BIGINT,
  pay_order_gmv_30d BIGINT,
  pay_order_gmv_acc BIGINT,
  refund_order_gmv_1d BIGINT,
  refund_order_gmv_7d BIGINT,
  refund_order_gmv_30d BIGINT,
  refund_order_gmv_acc BIGINT,
  ecommerce_pay_order_count_1d BIGINT,
  ecommerce_pay_order_count_7d BIGINT,
  ecommerce_pay_order_count_30d BIGINT,
  ecommerce_pay_order_count_acc BIGINT,
  ecommerce_refund_order_count_1d BIGINT,
  ecommerce_refund_order_count_7d BIGINT,
  ecommerce_refund_order_count_30d BIGINT,
  ecommerce_refund_order_count_acc BIGINT,
  ecommerce_pay_order_gmv_1d BIGINT,
  ecommerce_pay_order_gmv_7d BIGINT,
  ecommerce_pay_order_gmv_30d BIGINT,
  ecommerce_pay_order_gmv_acc BIGINT,
  ecommerce_refund_order_gmv_1d BIGINT,
  ecommerce_refund_order_gmv_7d BIGINT,
  ecommerce_refund_order_gmv_30d BIGINT,
  ecommerce_refund_order_gmv_acc BIGINT,
  short_video_pay_order_count_1d BIGINT,
  short_video_pay_order_count_7d BIGINT,
  short_video_pay_order_count_30d BIGINT,
  short_video_pay_order_count_acc BIGINT,
  short_video_refund_order_count_1d BIGINT,
  short_video_refund_order_count_7d BIGINT,
  short_video_refund_order_count_30d BIGINT,
  short_video_refund_order_count_acc BIGINT,
  short_video_pay_order_gmv_1d BIGINT,
  short_video_pay_order_gmv_7d BIGINT,
  short_video_pay_order_gmv_30d BIGINT,
  short_video_pay_order_gmv_acc BIGINT,
  short_video_refund_order_gmv_1d BIGINT,
  short_video_refund_order_gmv_7d BIGINT,
  short_video_refund_order_gmv_30d BIGINT,
  short_video_refund_order_gmv_acc BIGINT,
  live_pay_order_count_1d BIGINT,
  live_pay_order_count_7d BIGINT,
  live_pay_order_count_30d BIGINT,
  live_pay_order_count_acc BIGINT,
  live_refund_order_count_1d BIGINT,
  live_refund_order_count_7d BIGINT,
  live_refund_order_count_30d BIGINT,
  live_refund_order_count_acc BIGINT,
  live_pay_order_gmv_1d BIGINT,
  live_pay_order_gmv_7d BIGINT,
  live_pay_order_gmv_30d BIGINT,
  live_pay_order_gmv_acc BIGINT,
  live_refund_order_gmv_1d BIGINT,
  live_refund_order_gmv_7d BIGINT,
  live_refund_order_gmv_30d BIGINT,
  live_refund_order_gmv_acc BIGINT,
  PRIMARY KEY(dt,advertiser_id) NOT ENFORCED
) PARTITIONED BY(dt) WITH ('bucket'='2','file.format'='parquet');
CREATE TABLE dm_unit_df (
  dt STRING,unit_id BIGINT,unit_name STRING,
  delivery_count_1d BIGINT,
  delivery_count_7d BIGINT,
  delivery_count_30d BIGINT,
  delivery_count_acc BIGINT,
  impression_count_1d BIGINT,
  impression_count_7d BIGINT,
  impression_count_30d BIGINT,
  impression_count_acc BIGINT,
  click_count_1d BIGINT,
  click_count_7d BIGINT,
  click_count_30d BIGINT,
  click_count_acc BIGINT,
  conversion_count_1d BIGINT,
  conversion_count_7d BIGINT,
  conversion_count_30d BIGINT,
  conversion_count_acc BIGINT,
  cost_1d BIGINT,
  cost_7d BIGINT,
  cost_30d BIGINT,
  cost_acc BIGINT,
  closed_cost_1d BIGINT,
  closed_cost_7d BIGINT,
  closed_cost_30d BIGINT,
  closed_cost_acc BIGINT,
  pay_order_count_1d BIGINT,
  pay_order_count_7d BIGINT,
  pay_order_count_30d BIGINT,
  pay_order_count_acc BIGINT,
  refund_order_count_1d BIGINT,
  refund_order_count_7d BIGINT,
  refund_order_count_30d BIGINT,
  refund_order_count_acc BIGINT,
  pay_order_gmv_1d BIGINT,
  pay_order_gmv_7d BIGINT,
  pay_order_gmv_30d BIGINT,
  pay_order_gmv_acc BIGINT,
  refund_order_gmv_1d BIGINT,
  refund_order_gmv_7d BIGINT,
  refund_order_gmv_30d BIGINT,
  refund_order_gmv_acc BIGINT,
  ecommerce_pay_order_count_1d BIGINT,
  ecommerce_pay_order_count_7d BIGINT,
  ecommerce_pay_order_count_30d BIGINT,
  ecommerce_pay_order_count_acc BIGINT,
  ecommerce_refund_order_count_1d BIGINT,
  ecommerce_refund_order_count_7d BIGINT,
  ecommerce_refund_order_count_30d BIGINT,
  ecommerce_refund_order_count_acc BIGINT,
  ecommerce_pay_order_gmv_1d BIGINT,
  ecommerce_pay_order_gmv_7d BIGINT,
  ecommerce_pay_order_gmv_30d BIGINT,
  ecommerce_pay_order_gmv_acc BIGINT,
  ecommerce_refund_order_gmv_1d BIGINT,
  ecommerce_refund_order_gmv_7d BIGINT,
  ecommerce_refund_order_gmv_30d BIGINT,
  ecommerce_refund_order_gmv_acc BIGINT,
  short_video_pay_order_count_1d BIGINT,
  short_video_pay_order_count_7d BIGINT,
  short_video_pay_order_count_30d BIGINT,
  short_video_pay_order_count_acc BIGINT,
  short_video_refund_order_count_1d BIGINT,
  short_video_refund_order_count_7d BIGINT,
  short_video_refund_order_count_30d BIGINT,
  short_video_refund_order_count_acc BIGINT,
  short_video_pay_order_gmv_1d BIGINT,
  short_video_pay_order_gmv_7d BIGINT,
  short_video_pay_order_gmv_30d BIGINT,
  short_video_pay_order_gmv_acc BIGINT,
  short_video_refund_order_gmv_1d BIGINT,
  short_video_refund_order_gmv_7d BIGINT,
  short_video_refund_order_gmv_30d BIGINT,
  short_video_refund_order_gmv_acc BIGINT,
  live_pay_order_count_1d BIGINT,
  live_pay_order_count_7d BIGINT,
  live_pay_order_count_30d BIGINT,
  live_pay_order_count_acc BIGINT,
  live_refund_order_count_1d BIGINT,
  live_refund_order_count_7d BIGINT,
  live_refund_order_count_30d BIGINT,
  live_refund_order_count_acc BIGINT,
  live_pay_order_gmv_1d BIGINT,
  live_pay_order_gmv_7d BIGINT,
  live_pay_order_gmv_30d BIGINT,
  live_pay_order_gmv_acc BIGINT,
  live_refund_order_gmv_1d BIGINT,
  live_refund_order_gmv_7d BIGINT,
  live_refund_order_gmv_30d BIGINT,
  live_refund_order_gmv_acc BIGINT,
  PRIMARY KEY(dt,unit_id) NOT ENFORCED
) PARTITIONED BY(dt) WITH ('bucket'='2','file.format'='parquet');
CREATE TABLE dm_creative_df (
  dt STRING,creative_id BIGINT,creative_name STRING,
  delivery_count_1d BIGINT,
  delivery_count_7d BIGINT,
  delivery_count_30d BIGINT,
  delivery_count_acc BIGINT,
  impression_count_1d BIGINT,
  impression_count_7d BIGINT,
  impression_count_30d BIGINT,
  impression_count_acc BIGINT,
  click_count_1d BIGINT,
  click_count_7d BIGINT,
  click_count_30d BIGINT,
  click_count_acc BIGINT,
  conversion_count_1d BIGINT,
  conversion_count_7d BIGINT,
  conversion_count_30d BIGINT,
  conversion_count_acc BIGINT,
  cost_1d BIGINT,
  cost_7d BIGINT,
  cost_30d BIGINT,
  cost_acc BIGINT,
  closed_cost_1d BIGINT,
  closed_cost_7d BIGINT,
  closed_cost_30d BIGINT,
  closed_cost_acc BIGINT,
  pay_order_count_1d BIGINT,
  pay_order_count_7d BIGINT,
  pay_order_count_30d BIGINT,
  pay_order_count_acc BIGINT,
  refund_order_count_1d BIGINT,
  refund_order_count_7d BIGINT,
  refund_order_count_30d BIGINT,
  refund_order_count_acc BIGINT,
  pay_order_gmv_1d BIGINT,
  pay_order_gmv_7d BIGINT,
  pay_order_gmv_30d BIGINT,
  pay_order_gmv_acc BIGINT,
  refund_order_gmv_1d BIGINT,
  refund_order_gmv_7d BIGINT,
  refund_order_gmv_30d BIGINT,
  refund_order_gmv_acc BIGINT,
  ecommerce_pay_order_count_1d BIGINT,
  ecommerce_pay_order_count_7d BIGINT,
  ecommerce_pay_order_count_30d BIGINT,
  ecommerce_pay_order_count_acc BIGINT,
  ecommerce_refund_order_count_1d BIGINT,
  ecommerce_refund_order_count_7d BIGINT,
  ecommerce_refund_order_count_30d BIGINT,
  ecommerce_refund_order_count_acc BIGINT,
  ecommerce_pay_order_gmv_1d BIGINT,
  ecommerce_pay_order_gmv_7d BIGINT,
  ecommerce_pay_order_gmv_30d BIGINT,
  ecommerce_pay_order_gmv_acc BIGINT,
  ecommerce_refund_order_gmv_1d BIGINT,
  ecommerce_refund_order_gmv_7d BIGINT,
  ecommerce_refund_order_gmv_30d BIGINT,
  ecommerce_refund_order_gmv_acc BIGINT,
  short_video_pay_order_count_1d BIGINT,
  short_video_pay_order_count_7d BIGINT,
  short_video_pay_order_count_30d BIGINT,
  short_video_pay_order_count_acc BIGINT,
  short_video_refund_order_count_1d BIGINT,
  short_video_refund_order_count_7d BIGINT,
  short_video_refund_order_count_30d BIGINT,
  short_video_refund_order_count_acc BIGINT,
  short_video_pay_order_gmv_1d BIGINT,
  short_video_pay_order_gmv_7d BIGINT,
  short_video_pay_order_gmv_30d BIGINT,
  short_video_pay_order_gmv_acc BIGINT,
  short_video_refund_order_gmv_1d BIGINT,
  short_video_refund_order_gmv_7d BIGINT,
  short_video_refund_order_gmv_30d BIGINT,
  short_video_refund_order_gmv_acc BIGINT,
  live_pay_order_count_1d BIGINT,
  live_pay_order_count_7d BIGINT,
  live_pay_order_count_30d BIGINT,
  live_pay_order_count_acc BIGINT,
  live_refund_order_count_1d BIGINT,
  live_refund_order_count_7d BIGINT,
  live_refund_order_count_30d BIGINT,
  live_refund_order_count_acc BIGINT,
  live_pay_order_gmv_1d BIGINT,
  live_pay_order_gmv_7d BIGINT,
  live_pay_order_gmv_30d BIGINT,
  live_pay_order_gmv_acc BIGINT,
  live_refund_order_gmv_1d BIGINT,
  live_refund_order_gmv_7d BIGINT,
  live_refund_order_gmv_30d BIGINT,
  live_refund_order_gmv_acc BIGINT,
  PRIMARY KEY(dt,creative_id) NOT ENFORCED
) PARTITIONED BY(dt) WITH ('bucket'='2','file.format'='parquet');

